export const ReferralActionEnum = Object.freeze({
  CREATED: 'CREATED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  MORE_INFO_REQUESTED: 'MORE_INFO_REQUESTED',
  INFO_PROVIDED: 'INFO_PROVIDED',
  CLOSED: 'CLOSED'
});